// import { ContextApi } from "./data/hooks/ContextApi";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";

const metadata = {
  title: "Claquete | Filmes",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
      <html lang="pt-br">
        <body className="mx-auto">
          <main>{children}</main>
        </body>
      </html>
  );
}
