"use client";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { ContextApi } from "./api/ContextApi";

const metadata = {
  title: "Claquete | Filmes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ContextApi>
      <html lang="pt-br">
        <body className="mx-auto">
          <main>{children}</main>
        </body>
      </html>
    </ContextApi>
  );
}
